---
- name: Install and configure Nginx
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx package using Amazon Extras
      command:
        cmd: sudo amazon-linux-extras install nginx1

    - name: Copy HTML file
      copy:
        content: |
          <html>
          <head>
              <title>Hello World</title>
          </head>
          <body>
              <h1>Hello World!</h1>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true
